### ISSUE TITLE
Build Failure Arduino: 1.8.13 (Windows Store 1.8.42.0) (Windows 10), Board: "Arduino Uno"

### ISSUE THREAD

**Issue by wimos-ai** [arduino-libraries/Arduino_AVRSTL#3]
**My code:**

#include <Arduino_AVRSTL.h>
#include \<array\>
#include \<iostream\>
void setup() {
  // put your setup code here, to run once:

}

void loop() {
  // put your main code here, to run repeatedly:

}

**Abbreviated Error Message:**
Arduino: 1.8.13 (Windows Store 1.8.42.0) (Windows 10), Board: "Arduino Uno"

C:\Users\willm\Documents\Arduino\libraries\Arduino_AVRSTL\src\del_ops.cpp:25:50: error: 'std::size_t' has not been declared

 _UCXXEXPORT void operator delete(void* ptr, std::size_t) throw(){

                                                  ^~~~~~

C:\Users\willm\Documents\Arduino\libraries\Arduino_AVRSTL\src\Arduino_AVRSTL.cpp: In function 'int arduino_putchar(char, FILE*)':

C:\Users\willm\Documents\Arduino\libraries\Arduino_AVRSTL\src\Arduino_AVRSTL.cpp:54:42: warning: unused parameter 'f' [-Wunused-parameter]

 static int arduino_putchar(char c, FILE* f) {

                                          ^

C:\Users\willm\Documents\Arduino\libraries\Arduino_AVRSTL\src\Arduino_AVRSTL.cpp: In function 'int arduino_getchar(FILE*)':

C:\Users\willm\Documents\Arduino\libraries\Arduino_AVRSTL\src\Arduino_AVRSTL.cpp:65:34: warning: unused parameter 'f' [-Wunused-parameter]

 static int arduino_getchar(FILE *f) {

                                  ^

Using library Arduino_AVRSTL at version 1.2.4 in folder: C:\Users\willm\Documents\Arduino\libraries\Arduino_AVRSTL 

exit status 1

Error compiling for board Arduino Uno.

Installed Library from Arduino Library Downloader

**Comment by BCsabaEngine** [comment]
Same problem with arduino_cli.

**Comment by ajh123** [comment]
Same with the IDE from the website on macos

**Comment by GabrieleCicconetti** [comment]
@ajh123 @BCsabaEngine @wimos-ai nothing on this? :((

**Comment by BCsabaEngine** [comment]
> @ajh123 @BCsabaEngine @wimos-ai nothing on this? :((

I have left the usage of this lib, I use specific libs (instead of all in one) if needed: stacklist with type, etc.

**Comment by GabrieleCicconetti** [comment]
@BCsabaEngine thank you for your response? Can you please clarify i little more? 
Do you write your own libs?

**Comment by BCsabaEngine** [comment]
> @BCsabaEngine thank you for your response :) Can you please clarify i little more? Do you write your own libs?

Or use an existing one, ex. for dynamic list: https://github.com/luisllamasbinaburo/Arduino-List

**Comment by aentinger** [comment]
Sorry for the long drag, the fix was already in, just a new release was necessary ... https://github.com/arduino-libraries/Arduino_AVRSTL/releases/tag/1.2.5.
