### ISSUE TITLE
Compile failure - compat issue w/arduino mega2560

### ISSUE THREAD

**Issue by ldmtwo** [arduino-libraries/Arduino_AVRSTL#4]
Repro:
#include <Arduino_AVRSTL.h>  
#include <map>

FYI the other STLs also have similar issues. I'm using only standard out of the box Arduino IDE and devices.

C:\Users\LD\Documents\Arduino\libraries\Arduino_AVRSTL\src\del_opvnt.cpp:25:58: error: 'nothrow_t' in namespace 'std' does not name a type
 _UCXXEXPORT void operator delete[](void* ptr, const std::nothrow_t& ) throw(){
                                                          ^~~~~~~~~
C:\Users\LD\Documents\Arduino\libraries\Arduino_AVRSTL\src\del_ops.cpp:25:50: error: 'std::size_t' has not been declared
 _UCXXEXPORT void operator delete(void* ptr, std::size_t) throw(){
                                                  ^~~~~~
C:\Users\LD\Documents\Arduino\libraries\Arduino_AVRSTL\src\del_opvs.cpp:25:53: error: 'std::size_t' has not been declared
 _UCXXEXPORT void operator delete[](void * ptr, std::size_t) throw(){
                                                     ^~~~~~
C:\Users\LD\Documents\Arduino\libraries\Arduino_AVRSTL\src\del_opnt.cpp:25:56: error: 'nothrow_t' in namespace 'std' does not name a type
 _UCXXEXPORT void operator delete(void* ptr, const std::nothrow_t& ) throw() {
                                                        ^~~~~~~~~
exit status 1
Error compiling for board Arduino Mega or Mega 2560.

**Comment by aentinger** [comment]
Fixed by https://github.com/arduino-libraries/Arduino_AVRSTL/releases/tag/1.2.5.
